<!DOCTYPE HTML> 
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>@tutanxomon</title>
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
	
	<link href="/js/bubble/jquery.bubblepopup.v2.3.1.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="/js/reveal/reveal.css" />
	<link rel="stylesheet" type="text/css" href="/js/terminal/jquery.terminal.css" />
	<link rel="stylesheet" type="text/css" href="/style.css" media="all" />
	
	<script src="/js/jquery.js" type="text/javascript"></script>
	<script src="/js/bubble/jquery.bubblepopup.v2.3.1.min.js" type="text/javascript"></script>
	<script src="/js/reveal/jquery.reveal.js" type="text/javascript"></script>
	<script src="/js/terminal/jquery.terminal-0.3.3.js" type="text/javascript"></script>
	<script src="/js/script.js" type="text/javascript"></script>
</head>
<body>
	<header class="no-cell">
		<h1><strong>Маша,</strong> поздравляем с днём рождения! </h1>
	</header>
	<script>
		var wishes = <?php echo json_encode($wishes); ?>;
	</script>
	<div id="add-wish" class="reveal-modal">
	     <h2>Поздравить Машу:</h2>
	     <form method="post">
	     	<label for="name">Имя:</label><br />
	     	<input type="text" name="name" /><br />
	     	<label for="text">Поздравление:</label><br />
	     	<textarea name="text"></textarea><br />
	     	<input type="hidden" name="position" />
	     	<input type="submit" name="submit" value="подарить">
	     </form>
	     <a class="close-reveal-modal">&#215;</a>
	</div>
	<a href="#" data-reveal-id="add-wish" class="button green-button no-cell">Подарить единорога</a>
	<div id="terminal"></div>
</body>
</html>